/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as DealIdRouteImport } from './routes/deal.$id'
import { Route as CreatorIdRouteImport } from './routes/creator.$id'
import { Route as BrandIdRouteImport } from './routes/brand.$id'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth.update-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ReportIdSuccessRouteImport } from './routes/report.$id.success'
import { Route as DashboardCollectionIdRouteImport } from './routes/dashboard.collection.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DealIdRoute = DealIdRouteImport.update({
  id: '/deal/$id',
  path: '/deal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorIdRoute = CreatorIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CreatorRoute,
} as any)
const BrandIdRoute = BrandIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BrandRoute,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ReportIdSuccessRoute = ReportIdSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ReportIdRoute,
} as any)
const DashboardCollectionIdRoute = DashboardCollectionIdRouteImport.update({
  id: '/dashboard/collection/$id',
  path: '/dashboard/collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/brand': typeof BrandRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/creator': typeof CreatorRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/brand/$id': typeof BrandIdRoute
  '/creator/$id': typeof CreatorIdRoute
  '/deal/$id': typeof DealIdRoute
  '/report/$id': typeof ReportIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/collection/$id': typeof DashboardCollectionIdRoute
  '/report/$id/success': typeof ReportIdSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/brand': typeof BrandRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/creator': typeof CreatorRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/brand/$id': typeof BrandIdRoute
  '/creator/$id': typeof CreatorIdRoute
  '/deal/$id': typeof DealIdRoute
  '/report/$id': typeof ReportIdRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/collection/$id': typeof DashboardCollectionIdRoute
  '/report/$id/success': typeof ReportIdSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/brand': typeof BrandRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/creator': typeof CreatorRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/brand/$id': typeof BrandIdRoute
  '/creator/$id': typeof CreatorIdRoute
  '/deal/$id': typeof DealIdRoute
  '/report/$id': typeof ReportIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/collection/$id': typeof DashboardCollectionIdRoute
  '/report/$id/success': typeof ReportIdSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/brand'
    | '/campaigns'
    | '/creator'
    | '/marketplace'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/terms'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/update-password'
    | '/brand/$id'
    | '/creator/$id'
    | '/deal/$id'
    | '/report/$id'
    | '/dashboard/'
    | '/dashboard/collection/$id'
    | '/report/$id/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/brand'
    | '/campaigns'
    | '/creator'
    | '/marketplace'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/terms'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/update-password'
    | '/brand/$id'
    | '/creator/$id'
    | '/deal/$id'
    | '/report/$id'
    | '/dashboard'
    | '/dashboard/collection/$id'
    | '/report/$id/success'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/brand'
    | '/campaigns'
    | '/creator'
    | '/marketplace'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/terms'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/update-password'
    | '/brand/$id'
    | '/creator/$id'
    | '/deal/$id'
    | '/report/$id'
    | '/dashboard/'
    | '/dashboard/collection/$id'
    | '/report/$id/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRouteWithChildren
  BrandRoute: typeof BrandRouteWithChildren
  CampaignsRoute: typeof CampaignsRoute
  CreatorRoute: typeof CreatorRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  DealIdRoute: typeof DealIdRoute
  ReportIdRoute: typeof ReportIdRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCollectionIdRoute: typeof DashboardCollectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal/$id': {
      id: '/deal/$id'
      path: '/deal/$id'
      fullPath: '/deal/$id'
      preLoaderRoute: typeof DealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$id': {
      id: '/creator/$id'
      path: '/$id'
      fullPath: '/creator/$id'
      preLoaderRoute: typeof CreatorIdRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/brand/$id': {
      id: '/brand/$id'
      path: '/$id'
      fullPath: '/brand/$id'
      preLoaderRoute: typeof BrandIdRouteImport
      parentRoute: typeof BrandRoute
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/report/$id/success': {
      id: '/report/$id/success'
      path: '/success'
      fullPath: '/report/$id/success'
      preLoaderRoute: typeof ReportIdSuccessRouteImport
      parentRoute: typeof ReportIdRoute
    }
    '/dashboard/collection/$id': {
      id: '/dashboard/collection/$id'
      path: '/dashboard/collection/$id'
      fullPath: '/dashboard/collection/$id'
      preLoaderRoute: typeof DashboardCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BrandRouteChildren {
  BrandIdRoute: typeof BrandIdRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandIdRoute: BrandIdRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

interface CreatorRouteChildren {
  CreatorIdRoute: typeof CreatorIdRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorIdRoute: CreatorIdRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

interface ReportIdRouteChildren {
  ReportIdSuccessRoute: typeof ReportIdSuccessRoute
}

const ReportIdRouteChildren: ReportIdRouteChildren = {
  ReportIdSuccessRoute: ReportIdSuccessRoute,
}

const ReportIdRouteWithChildren = ReportIdRoute._addFileChildren(
  ReportIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRouteWithChildren,
  BrandRoute: BrandRouteWithChildren,
  CampaignsRoute: CampaignsRoute,
  CreatorRoute: CreatorRouteWithChildren,
  MarketplaceRoute: MarketplaceRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  DealIdRoute: DealIdRoute,
  ReportIdRoute: ReportIdRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCollectionIdRoute: DashboardCollectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
